# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BugTracker', '0002_auto_20170602_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='creationDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
